### ISSUE TITLE
Cognito android

### ISSUE THREAD

**Issue by deepa14bharti** [keivanK1/Cognito-Android-Studio#1]
Hi, 

I am getting an issue to integrate cognito signup even in your project also please check and help me.

com.amazonaws.services.cognitoidentityprovider.model.InvalidParameterException: App client 45f45bitpl1u3n2pku8fm0r3im is not configured for secret but secret hash was received (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: InvalidParameterException; Request ID: e0af537f-a973-49c2-afa6-7c629fade1fd)

**Comment by keivanK1** [comment]
Make sure you have used App Client from AWS in the app
